import type { Project, Task, Notification, GovernanceItem } from "@/types";

export const DEMO_USER = {
  id: "demo",
  name: "Ahmet Yılmaz",
  email: "demo@pixanto.app",
  role: "admin" as const,
  language: "tr" as const,
  title: "Proje Müdürü",
  department: "Yazılım",
};

export const DEMO_PROJECTS: Project[] = [
  {
    id: "1",
    name: "E-Ticaret Platformu",
    description: "Yeni nesil B2B e-ticaret platformu geliştirme projesi",
    status: "active",
    priority: "high",
    projectType: "agile",
    currentSprint: 3,
    startDate: "2026-01-15",
    endDate: "2026-06-30",
    progress: 45,
    budget: 120000,
    budgetUsed: 54000,
    managerId: "demo",
    members: [],
    tags: ["web", "react", "backend"],
    createdAt: "2026-01-15T09:00:00Z",
    updatedAt: "2026-03-10T14:30:00Z",
  },
  {
    id: "2",
    name: "Mobil Uygulama Redesign",
    description: "iOS ve Android uygulamalarının yeniden tasarımı",
    status: "at_risk",
    priority: "critical",
    projectType: "waterfall",
    startDate: "2026-02-01",
    endDate: "2026-04-30",
    progress: 62,
    budget: 80000,
    budgetUsed: 71000,
    managerId: "demo",
    members: [],
    tags: ["mobile", "design", "ux"],
    createdAt: "2026-02-01T09:00:00Z",
    updatedAt: "2026-03-18T16:00:00Z",
  },
  {
    id: "3",
    name: "CRM Entegrasyonu",
    description: "Mevcut CRM sistemi ile API entegrasyonu",
    status: "active",
    priority: "medium",
    projectType: "agile",
    currentSprint: 1,
    startDate: "2026-03-01",
    endDate: "2026-05-15",
    progress: 28,
    budget: 45000,
    budgetUsed: 12000,
    managerId: "demo",
    members: [],
    tags: ["api", "integration"],
    createdAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-03-19T11:00:00Z",
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: "t1", projectId: "1", title: "Ana sayfa tasarımını tamamla",
    description: "Hero section ve feature bölümlerini Figma'dan kodla",
    status: "in_progress", priority: "high", issueType: "task",
    assigneeId: undefined, startDate: "2026-03-15", dueDate: "2026-03-25",
    estimatedHours: 8, loggedHours: 5, storyPoints: 5, sprint: 3,
    tags: ["frontend", "design"], subtasks: [
      { id: "s1", title: "Hero section", completed: true },
      { id: "s2", title: "Feature cards", completed: true },
      { id: "s3", title: "CTA bölümü", completed: false },
    ],
    dependencies: [], attachments: [], comments: [],
    createdAt: "2026-03-01T09:00:00Z", updatedAt: "2026-03-19T10:00:00Z", order: 0,
  },
  {
    id: "t2", projectId: "1", title: "Kullanıcı auth API'si",
    description: "JWT tabanlı kimlik doğrulama sistemi",
    status: "done", priority: "critical", issueType: "task",
    assigneeId: undefined, startDate: "2026-02-25", dueDate: "2026-03-10",
    estimatedHours: 12, loggedHours: 14, storyPoints: 8, sprint: 2,
    tags: ["backend", "api"], subtasks: [], dependencies: [], attachments: [], comments: [],
    createdAt: "2026-02-20T09:00:00Z", updatedAt: "2026-03-10T17:00:00Z", order: 0,
  },
  {
    id: "t3", projectId: "1", title: "Ürün listesi sayfası",
    description: "Filtreleme ve arama özellikleriyle ürün listeleme",
    status: "todo", priority: "medium", issueType: "story",
    assigneeId: undefined, startDate: "2026-03-20", dueDate: "2026-04-05",
    estimatedHours: 16, loggedHours: 0, storyPoints: 13, sprint: 3,
    tags: ["frontend"], subtasks: [], dependencies: ["t2"], attachments: [], comments: [],
    createdAt: "2026-03-05T09:00:00Z", updatedAt: "2026-03-05T09:00:00Z", order: 1,
  },
  {
    id: "t4", projectId: "1", title: "Ödeme entegrasyonu",
    description: "Stripe ve iyzico entegrasyonu",
    status: "todo", priority: "high", issueType: "story",
    assigneeId: undefined, startDate: "2026-04-01", dueDate: "2026-04-15",
    estimatedHours: 20, loggedHours: 0, storyPoints: undefined, sprint: undefined,
    tags: ["backend", "payment"], subtasks: [], dependencies: ["t2"], attachments: [], comments: [],
    createdAt: "2026-03-05T09:00:00Z", updatedAt: "2026-03-05T09:00:00Z", order: 2,
  },
  {
    id: "t5", projectId: "1", title: "Code review - Auth modülü",
    description: "Auth API kodlarının gözden geçirilmesi",
    status: "review", priority: "medium", issueType: "task",
    assigneeId: undefined, startDate: "2026-03-19", dueDate: "2026-03-22",
    estimatedHours: 4, loggedHours: 2, storyPoints: undefined, sprint: 3,
    tags: ["review"], subtasks: [], dependencies: ["t2"], attachments: [], comments: [],
    createdAt: "2026-03-11T09:00:00Z", updatedAt: "2026-03-19T09:00:00Z", order: 0,
  },
  {
    id: "t6", projectId: "2", title: "UI komponent kütüphanesi",
    description: "Yeni tasarım sistemine göre komponentler",
    status: "in_progress", priority: "high", issueType: "task",
    assigneeId: undefined, startDate: "2026-03-01", dueDate: "2026-03-28",
    estimatedHours: 24, loggedHours: 18,
    tags: ["mobile", "design"], subtasks: [], dependencies: [], attachments: [], comments: [],
    phase: "design", createdAt: "2026-02-15T09:00:00Z", updatedAt: "2026-03-19T14:00:00Z", order: 0,
  },
  {
    id: "t7", projectId: "2", title: "Kullanıcı araştırması ve persona analizi",
    description: "Hedef kullanıcı kitlesi için araştırma",
    status: "done", priority: "high", issueType: "story",
    assigneeId: undefined, startDate: "2026-02-01", dueDate: "2026-02-15",
    estimatedHours: 16, loggedHours: 18,
    tags: ["research", "ux"],
    subtasks: [
      { id: "s7a", title: "Anket hazırlama", completed: true },
      { id: "s7b", title: "Görüşme yapma (10 kullanıcı)", completed: true },
      { id: "s7c", title: "Persona dokümanı", completed: true },
    ],
    dependencies: [], attachments: [], comments: [],
    phase: "requirements", createdAt: "2026-02-01T09:00:00Z", updatedAt: "2026-02-15T17:00:00Z", order: 0,
  },
  {
    id: "t8", projectId: "2", title: "Gereksinim dokümanı (PRD)",
    description: "Ürün gereksinim dokümanının hazırlanması",
    status: "done", priority: "critical", issueType: "task",
    assigneeId: undefined, startDate: "2026-02-06", dueDate: "2026-02-20",
    estimatedHours: 12, loggedHours: 14,
    tags: ["documentation"], subtasks: [], dependencies: ["t7"], attachments: [], comments: [],
    phase: "requirements", createdAt: "2026-02-05T09:00:00Z", updatedAt: "2026-02-20T17:00:00Z", order: 1,
  },
  {
    id: "t9", projectId: "2", title: "Wireframe tasarımları",
    description: "Tüm ekranlar için low-fi wireframe",
    status: "done", priority: "high", issueType: "task",
    assigneeId: undefined, startDate: "2026-02-21", dueDate: "2026-03-05",
    estimatedHours: 20, loggedHours: 22,
    tags: ["design", "wireframe"],
    subtasks: [
      { id: "s9a", title: "Ana ekranlar", completed: true },
      { id: "s9b", title: "Akış diyagramları", completed: true },
    ],
    dependencies: ["t8"], attachments: [], comments: [],
    phase: "design", createdAt: "2026-02-21T09:00:00Z", updatedAt: "2026-03-05T17:00:00Z", order: 0,
  },
  {
    id: "t10", projectId: "2", title: "Native modül geliştirme",
    description: "iOS ve Android native bileşenlerin kodlanması",
    status: "todo", priority: "high", issueType: "task",
    assigneeId: undefined, startDate: "2026-03-29", dueDate: "2026-04-10",
    estimatedHours: 40, loggedHours: 0,
    tags: ["mobile", "native"], subtasks: [], dependencies: ["t6"], attachments: [], comments: [],
    phase: "development", createdAt: "2026-03-10T09:00:00Z", updatedAt: "2026-03-10T09:00:00Z", order: 0,
  },
  {
    id: "t11", projectId: "2", title: "Entegrasyon testleri",
    description: "API ve UI entegrasyon test senaryoları",
    status: "todo", priority: "medium", issueType: "test",
    assigneeId: undefined, startDate: "2026-04-11", dueDate: "2026-04-20",
    estimatedHours: 16, loggedHours: 0,
    tags: ["testing", "qa"], subtasks: [], dependencies: ["t10"], attachments: [], comments: [],
    phase: "testing", createdAt: "2026-03-10T09:00:00Z", updatedAt: "2026-03-10T09:00:00Z", order: 0,
  },
  {
    id: "t12", projectId: "2", title: "App Store & Play Store yayını",
    description: "Uygulamanın mağazalara yüklenmesi ve onay süreci",
    status: "todo", priority: "critical", issueType: "task",
    assigneeId: undefined, startDate: "2026-04-21", dueDate: "2026-04-28",
    estimatedHours: 8, loggedHours: 0,
    tags: ["deployment", "release"], subtasks: [], dependencies: ["t11"], attachments: [], comments: [],
    phase: "deployment", createdAt: "2026-03-10T09:00:00Z", updatedAt: "2026-03-10T09:00:00Z", order: 0,
  },
];

export const DEMO_GOVERNANCE: GovernanceItem[] = [
  {
    id: "g1", projectId: "2", category: "charter",
    title: "Mobil Uygulama Redesign Proje Tüzüğü",
    description: "Projenin kapsamı, hedefleri, paydaşları ve temel kısıtları tanımlanmıştır.",
    status: "approved", owner: "Ahmet Yılmaz", createdAt: "2026-02-01T09:00:00Z",
  },
  {
    id: "g2", projectId: "2", category: "meeting",
    title: "Şubat Yürütme Komitesi Toplantısı",
    description: "Aylık ilerleme değerlendirme toplantısı",
    status: "completed", owner: "Zeynep Kaya",
    meetingDate: "2026-02-28T14:00:00Z",
    attendees: ["Ahmet Yılmaz", "Zeynep Kaya", "Mehmet Demir"],
    minutes: "Tasarım fazı %100 tamamlandı. Geliştirme fazına geçildi.",
    createdAt: "2026-02-28T09:00:00Z",
  },
  {
    id: "g3", projectId: "2", category: "meeting",
    title: "Mart Yürütme Komitesi Toplantısı",
    description: "Geliştirme fazı ilerleme toplantısı",
    status: "scheduled", owner: "Zeynep Kaya",
    meetingDate: "2026-03-28T14:00:00Z",
    attendees: ["Ahmet Yılmaz", "Zeynep Kaya", "Mehmet Demir", "Ayşe Çelik"],
    createdAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "g4", projectId: "2", category: "risk",
    title: "Bütçe Aşımı Riski",
    description: "Mevcut harcama oranıyla proje bütçesinin aşılması riski.",
    status: "open", priority: "high", owner: "Ahmet Yılmaz",
    impact: "high", probability: "high",
    mitigationPlan: "Haftalık bütçe takibi yapılacak, gereksiz harcamalar kısıtlanacak.",
    createdAt: "2026-03-15T09:00:00Z",
  },
  {
    id: "g5", projectId: "2", category: "risk",
    title: "Kaynak Eksikliği",
    description: "iOS geliştirici pozisyonu için uygun kaynak bulunamama riski.",
    status: "mitigated", priority: "medium", owner: "Zeynep Kaya",
    impact: "medium", probability: "low",
    mitigationPlan: "Freelance geliştirici alternatifi değerlendirildi ve yedek plan oluşturuldu.",
    createdAt: "2026-02-10T09:00:00Z",
  },
  {
    id: "g6", projectId: "2", category: "change",
    title: "Dark Mode Özelliği Eklenmesi",
    description: "Kullanıcı geri bildirimleri doğrultusunda dark mode desteği.",
    status: "pending", priority: "medium", owner: "Mehmet Demir",
    requestedBy: "Ürün Yöneticisi",
    impactAssessment: "Tahmini 2 hafta ek geliştirme süresi ve ₺15.000 ek maliyet.",
    dueDate: "2026-03-25", createdAt: "2026-03-12T09:00:00Z",
  },
  {
    id: "g7", projectId: "2", category: "change",
    title: "Android Min SDK Versiyonu Güncelleme",
    description: "Android min SDK versiyonunun 21'den 24'e yükseltilmesi",
    status: "approved", priority: "low", owner: "Ayşe Çelik",
    requestedBy: "Teknik Lider",
    impactAssessment: "Yaklaşık %5 kullanıcı etkilenecek. Test coverage genişletilmeli.",
    createdAt: "2026-02-25T09:00:00Z",
  },
  {
    id: "g8", projectId: "2", category: "issue",
    title: "App Store Onay Süreci Gecikmesi",
    description: "Apple App Store inceleme sürecinin 2 haftaya kadar uzayabileceği öğrenildi.",
    status: "open", priority: "high", owner: "Ahmet Yılmaz",
    dueDate: "2026-04-10", createdAt: "2026-03-18T09:00:00Z",
  },
  {
    id: "g9", projectId: "2", category: "issue",
    title: "Tasarım Sistemi Uyumsuzluğu",
    description: "Bazı komponentler mevcut tasarım sistemi standartlarıyla uyumsuz.",
    status: "closed", priority: "medium", owner: "Mehmet Demir",
    createdAt: "2026-03-05T09:00:00Z",
  },
  {
    id: "g10", projectId: "2", category: "decision",
    title: "React Native Kullanımına Devam",
    description: "Flutter alternatifininin değerlendirilmesinin ardından React Native ile devam kararı.",
    status: "approved", owner: "Ahmet Yılmaz",
    decidedBy: "Yürütme Komitesi",
    rationale: "Mevcut ekip yetkinliği ve proje süresini kısaltma önceliği göz önünde bulundurularak React Native tercih edildi.",
    createdAt: "2026-02-05T09:00:00Z",
  },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: "n1", type: "task_assigned", title: "Görev Atandı",
    message: "\"Ana sayfa tasarımını tamamla\" görevi size atandı.",
    read: false, link: "/projeler/1", createdAt: "2026-03-19T10:00:00Z",
  },
  {
    id: "n2", type: "deadline", title: "Deadline Yaklaşıyor",
    message: "\"Code review - Auth modülü\" görevi 2 gün içinde sona eriyor.",
    read: false, link: "/projeler/1", createdAt: "2026-03-18T09:00:00Z",
  },
  {
    id: "n3", type: "budget_alert", title: "Bütçe Uyarısı",
    message: "\"Mobil Uygulama Redesign\" projesinin bütçesi %88 oranında kullanıldı.",
    read: true, link: "/projeler/2", createdAt: "2026-03-17T14:00:00Z",
  },
  {
    id: "n4", type: "comment", title: "Yeni Yorum",
    message: "Ayşe Kaya göreve yorum ekledi: \"Renk paletini güncelledim.\"",
    read: true, link: "/projeler/1", createdAt: "2026-03-16T16:30:00Z",
  },
];
